### ISSUE TITLE
As a user, I wanna store my last 3 score to compare and improve the speed and the quality of result

### ISSUE THREAD

**Issue by VinhLQ298** [nguyentracthanh/USTH-SE-2019#27]

**Comment by nguyentracthanh** [comment]
_**task:**_
### **Design**
- [x] create 3 variables to store last 3 score
- [x] Display them in 1 table on the screen (or a list)
- [ ] Clear the 4th variable to store the new score
### **Testing**
- [ ] Check whether the code can store the variables
- [ ] Check if the code can recall the value to show to the screen
- [ ] Sort the score in the descent order
### **High-level design**
- [ ] Design a table (or a list) on the left of the screen to show the scores
- [x] Optimize the code, delete the unnecessary code lines to reduce the system complexity 
### **Low-level design**
- [ ] Choose the design patterns
- [x] Build the function
- [ ] Apply then test the function
